[package]
name = "script-namer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
rayon = "1.10.0"
regex = "1.11.1"
rfd = "0.15.2"
walkdir = "2.5.0"

[profile.release]
lto = "fat"
opt-level = 3
strip = true
codegen-units = 1
